### ISSUE TITLE
Run container on ports other than 80 and 443

### ISSUE THREAD

**Issue by adelerhof** [aaronpowell/httpstatus#151]
I would like to run the container on different ports than 80 and 443. I want to run it on Kubernetes without root permissions, with the `runAsNonRoot` directive.
I tested it with changing the `EXPOSE` ports in the Dockerfile, as expected this doesn't work, I suppose because the application itself runs hardcoded on 80 and 443. It there a way I can change the source code and build it to run on different ports?

Thanks!

**Comment by adelerhof** [comment]
Thanks for this answer, I will test this and let you know.

**Comment by adelerhof** [comment]
I've got the pod running on Kubernetes, I had to rebuild the image.
I needed to add `USER $APP_UID` to run it with a non-root user, described below.

_Non-Root User Included By Default_

_The .NET Linux container images include a new non-root user named app with the UID 1654._
_The UID is provided in an environment variable, $APP_UID._
_You can opt into this new user by adding the line USER $APP_UID to your Dockerfile._

[New Features for .NET Container Images](https://github.com/dotnet/dotnet-docker/discussions/4995)

I also added in the deployment the environment variable you mentioned, as well as the port used:

```yml
apiVersion: apps/v1
kind: Deployment
...
spec:
...
    spec:
      containers:
      - name: httpstatus
...
        env:
        - name: ASPNETCORE_URLS
          value: http://*:5000
...
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
```

I only run the pod on `http` on port `5000`, `https` is handled by the ingress.

I hope this helps someone who also bumps into this issue.
Thanks again!
